input_folder: C:\dev\invade\firstpub-Platform\docs\1. Preface End facism\1. keep track\executive-orders
output_folder: C:\dev\invade\firstpub-Platform\docs\1. Preface End facism\1. keep
  track\executive-orders\outputs
instructions_file: C:\dev\invade\firstpub-Platform\docs\Lit Summery\instructions\Eo
  instructions.md
one_file_only: true
iterations_default: 1
runs:
- type: fpf
  provider: google
  model: gemini-2.5-flash
- type: fpf
  provider: google
  model: gemini-2.5-flash-lite
- type: fpf
  provider: openai
  model: gpt-5-mini
- type: fpf
  provider: openai
  model: gpt-5-nano
- type: fpf
  provider: openai
  model: o4-mini
# - type: fpf
#   provider: openaidp
#   model: o4-mini-deep-research
- type: gptr
  provider: google_genai
  model: gemini-2.5-flash
- type: gptr
  provider: google_genai
  model: gemini-2.5-flash-lite
# - type: gptr
#   provider: openai
#   model: gpt-4.1
# - type: gptr
#   provider: openai
#   model: gpt-4.1-mini
# - type: gptr
#   provider: openai
#   model: gpt-4.1-nano
# - type: gptr
#   provider: openai
#   model: gpt-4o
# - type: dr
#   provider: openai
#   model: gpt-5-mini
#   provider: openai
#   model: gpt-5-mini
# - type: dr
#   provider: google_genai
#   model: gemini-2.5-flash
# - type: dr
#   provider: google_genai
#   model: gemini-2.5-flash-lite
# - type: dr
#   provider: openai
#   model: gpt-4.1-mini
# - type: dr
#   provider: openai
#   model: gpt-4.1-nano
# - type: dr
#   provider: openai
#   model: gpt-4o
# - type: ma
#   model: gpt-4.1-mini
# - type: ma
  model: gpt-4.1-nano
- type: ma
  model: gpt-4o
- type: ma
  model: gpt-4o-mini
- type: ma
  model: o4-mini
concurrency:
  gpt_researcher:
    enabled: true
    max_concurrent_reports: 11
    launch_delay_seconds: 0.5
  multi_agent:
    enabled: true
    max_concurrent_runs: 4
    launch_delay_seconds: 0.5
policies:
  concurrency:
    gpt_researcher:
      enforce: false
      max_concurrent_reports_cap: 11
      launch_delay_seconds_min: 0.5
acm:
  log:
    forward_subprocess_output: false
eval:
  log:
    console_level: high
    file_level: Medium
  output_directory: gptr-eval-process/final_reports
  export_directory: gptr-eval-process/exports
  auto_run: true
guidelines_file: C:\Users\kjhgf\OneDrive\Documents\Cline\silky\api_cost_multiplier\test\report
  must be in spanish.txt
